services:
  postgres-db:
    container_name:  postgres-db-container
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  nestjs-server:
    container_name: nestjs-server-container
    image: my-nestjs-app:1.3
    ports: 
      - 4000:4000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres-db:
        condition: service_healthy
        restart: true