name: E2E Testing and Docker deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/main.yml'
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Start Infrastructure (Docker Compose)
        run: docker compose -f docker-compose.yml --profile test up -d postgres-db minio

      - name: Wait for Health
        run: sleep 15 

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.13.0'

      - name: Install and Test
        run: |
          npm install
          npm run prisma:start
          npm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_PUBLIC_ENDPOINT: ${{ secrets.S3_PUBLIC_ENDPOINT }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          STRIPE_ENDPOINT: ${{ secrets.STRIPE_ENDPOINT }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: e2e-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-server:latest